sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: graduation_design
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAuprHN8sMD78sPggMn
    access-key-secret: 0GXLrfCHDne9Matykjvj3WlsDzdxSh
    bucket-name: yyqnews
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  sms:
    accessKeyId: LTAI5tAuprHN8sMD78sPggMn
    accessKeySecret: 0GXLrfCHDne9Matykjvj3WlsDzdxSh
